[Feature] support partial update
StarRocks/starrocks-connector-for-apache-flink pull request #98
Opened 2022-06-02 03:17 UTC by xlfjcg

Use enablePartialUpdate or sink.enable-partial-update to open

Signed-off-by: xlfjcg <1937532871@qq.com>

2022-06-02 12:28 UTC, chaoyli approved these changes

2022-06-02 13:02 UTC, hffariel requested changes

2022-06-02 13:02 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
> +            if (sinkOptions.isEnablePartialUpdate()) {
isEnablePartialUpdate -> partialUpdateEnabled ?

2022-06-02 13:02 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
> +    public void enablePartialUpdate() {
no references of this method found.

2022-06-02 13:02 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
> +    public static final ConfigOption<Boolean> SINK_ENABLE_PARTIAL_UPDATE = ConfigOptions.key("sink.enable-partial-update")
Why don't just use sink.properties.partial_update instead?

2022-06-08 02:52 UTC, xlfjcg commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
> +            if (sinkOptions.isEnablePartialUpdate()) {
boolean field get method like isxxxx

2022-06-08 02:54 UTC, xlfjcg commented on src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
> +    public static final ConfigOption<Boolean> SINK_ENABLE_PARTIAL_UPDATE = ConfigOptions.key("sink.enable-partial-update")
partial update can just only set head in the moment, Here is the convenience for future expansion

2022-06-08 02:55 UTC, xlfjcg commented on src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
> +    public void enablePartialUpdate() {
custom job to can use

2022-06-17 11:36 UTC, waittttting commented
LGTM

2022-07-06 05:20 UTC, closed without merging